name: Build and Test Rock

on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install rockcraft --classic --edge
      - name: Build Rock
        run: |
          rockcraft pack --verbose
      - name: Upload built rock artifact
        uses: actions/upload-artifact@v4
        with:
          name: charmed-etcd-rock
          path: charmed-etcd_*.rock
  test:
    name: Test Rock
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download rock file
        uses: actions/download-artifact@v4
        with:
          name: charmed-etcd-rock
          path: .

      - name: Install required dependencies
        run: |
          sudo snap install docker
          sudo snap disable docker; sudo snap enable docker

          # skopeo
          sudo apt-get update -y && sudo apt-get install -y skopeo
          sudo snap install yq

      - name: Create local image
        run: |
          version="$(yq .version rockcraft.yaml)"
          sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:charmed-etcd_${version}_amd64.rock \
              docker-daemon:charmed-etcd:${version}

      - name: Start etcd run tests
        run: |
          version="$(yq .version rockcraft.yaml)"
          sudo docker run \
            -d --rm \
            -p 2379:2379 \
            --name etcd-test \
            charmed-etcd:"${version}"
          
          # wait a bit for it to fully initialize
          sleep 15s
          
          if ! sudo docker exec etcd-test etcdctl --endpoints=http://localhost:2379 put foo bar; then
            echo "etcd failed put test"
            exit 1
          fi

          VALUE=$(sudo docker exec etcd-test etcdctl --endpoints=http://localhost:2379 get foo --print-value-only)
          if [ "$VALUE" != "bar" ]; then
            echo "expected 'bar' but got '$VALUE'"
            exit 1
          fi

          if ! sudo docker exec etcd-test etcdctl --endpoints=http://localhost:2379 endpoint health | grep -q "is healthy"; then
            echo "etcd failed health check"
            exit 1
          fi
