name: Build and Test Rock

on:
  workflow_call:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Rock
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
      - name: Install dependencies
        run: |
          sudo snap install rockcraft --classic --edge
      - name: Build Rock
        run: |
          rockcraft pack --verbose
      - name: Upload built rock artifact
        uses: actions/upload-artifact@v4
        with:
          name: charmed-etcd-rock
          path: charmed-etcd_*.rock
  test:
    name: Test Rock
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download rock file
        uses: actions/download-artifact@v4
        with:
          name: charmed-etcd-rock
          path: .

      - name: Install required dependencies
        run: |
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

          # skopeo
          sudo apt-get update -y && sudo apt-get install -y skopeo
          sudo snap install yq

      - name: Create local image
        run: |
          version="$(yq .version rockcraft.yaml)"
          sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:charmed-etcd_${version}_amd64.rock \
              docker-daemon:charmed-etcd:${version}

      - name: Start etcd run tests
        run: |
          version="$(yq .version rockcraft.yaml)"
          docker network create etcd-net

          MEMBERS=(etcd0 etcd1 etcd2)
          INITIAL_CLUSTER=""
          for MEMBER in "${MEMBERS[@]}"; do
            INITIAL_CLUSTER+="${MEMBER}=http://${MEMBER}:2380,"
          done
          INITIAL_CLUSTER="${INITIAL_CLUSTER%,}"

          for MEMBER in "${MEMBERS[@]}"; do
             docker run -d --rm \
               --name "${MEMBER}" \
               --network etcd-net \
               -e ETCD_NAME="${MEMBER}" \
               -e ETCD_INITIAL_ADVERTISE_PEER_URLS="http://${MEMBER}:2380" \
               -e ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380" \
               -e ETCD_ADVERTISE_CLIENT_URLS="http://${MEMBER}:2379" \
               -e ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379" \
               -e ETCD_INITIAL_CLUSTER_TOKEN="etcd_cluster" \
               -e ETCD_INITIAL_CLUSTER="${INITIAL_CLUSTER}" \
               -e ETCD_INITIAL_CLUSTER_STATE=new \
               charmed-etcd:"${version}"
          done
          
          # wait a bit for it to fully initialize
          sleep 15s
          
          cluster=$(docker exec etcd0 etcdctl --endpoints=http://localhost:2379 member list)
          count=$(grep -c ', started,' <<< "$cluster")
          if [ "$count" -ne 3 ]; then
            echo "expected 3 members but got $count"
            exit 1
          fi

          if ! docker exec etcd0 etcdctl --endpoints=http://localhost:2379 put foo bar; then
            echo "etcd failed put test"
            exit 1
          fi

          sleep 2s

          VALUE=$(docker exec etcd1 etcdctl --endpoints=http://localhost:2379 get foo --print-value-only)
          if [ "$VALUE" != "bar" ]; then
            echo "expected 'bar' but got '$VALUE'"
            exit 1
          fi

          health-check(){
            local MEMBER="$1"
            if ! docker exec "${MEMBER}" etcdctl --endpoints=http://localhost:2379 endpoint health | grep -q "is healthy"; then
              echo "member ${MEMBER} failed health check"
              exit 1
            fi
          }

          health-check etcd0
          health-check etcd1
          health-check etcd2
